### PR TITLE
feat: add bigdl-llm demo for intel device

### PR DESCRIPTION
**Pull request by ai-liuys**
Hello, this code submission has been verified locally, and with the integration of the bigdl-llm acceleration framework, large models can run smoothly using integrated graphics cards. The steps for the related demo are provided in English comments. Merging this code into the branch will help students without dedicated graphics cards to more conveniently utilize the capabilities of the chatglm3 large model. 

Date: March 26, 2024 Location: Binjiang Research Institute, Zhejiang University.

### CODE REVIEW

**Comment by zRzRzRzRzRzRzR** [comment]
thank you! We will check it quickly

**Comment by zRzRzRzRzRzRzR** [comment]
can we contact you through wechat，we interact with Intel Engineer， something need to correct since the framework in Intel had changed

**Comment by ai-liuys** [comment]
I have already added you on WeChat, my name is Liu Yusheng. I have already told you "say hello".

**Comment by ai-liuys** [comment]
job is done !

**Comment by zRzRzRzRzRzRzR** [comment]
现在已经可以合并了吧，GPU部分测试了吗

**Comment by ai-liuys** [comment]
CPU 这部分代码可以合并了，GPU部分还在跟进中

**Pull request merged**
